//	the Game closeup template
IGNGamestore.views.gameCloseupTemplate = new Ext.XTemplate([
 		'<div id="closeup">',
				'<div id="leftColumn">',
					'<img src="{LargeIconUrl}" class="closeupBoxart" />',
					'<a href="{VendorGameUrl}" class="buy">${Price}</a>',
				'</div>',
				'<div id="rightColumn">',
					'<tpl if="inCollection == true">',
						'<a href="#{Id}" class="addToCollection added">Added to collection</a>',
 					'</tpl>',
 					'<tpl if="inCollection == false">',
						'<a href="#{Id}" class="addToCollection">Add to collection</a>',
					'</tpl>',
					'<h1>{Name}</h1>',
					'<h2>By {Developer}</h2>',
					'<h3>Released on {ReleaseDate}</h3>',
					'<ul class="ratingList">',
						'<li><strong>IGN: </strong><span class="rating rating_4">4</span></li>',
						'<li><strong>Community: </strong><span class="rating rating_4">4</span></li>',
					'</ul>',
					'<p>{Description}</p>',
					'<h3 class="recommendedGamesHeader">Other Games You\'ll Like</h3>',
					'<ul class="recommendedGames">',
						'<tpl for="RecommendedGames">',
							'<li><a href="#{Game.Id}" class="recommendedGamesLink"><img src="{Game.LargeIconUrl}" class="recommendedBoxart" /></a></li>',
						'</tpl>',
					'</ul>',
				'</div>',
			'</div>',
			'<ul class="detailsNav">',
					'<li><a href="#{Id}" class="loadComments active">Comments</a></li>',
					'<li><a href="#{Id}" class="loadCheats">Cheats</a></li>',
				'</ul>',
			'<div class="detailsContainer">',
				'<div id="comments" class="sectionContainer">',
					'<ul id="commentList">',
						'<tpl for="comments">',
							'<li class="dev_{dev}">',
								'<span class="commentName">posted by <span class="italic">unknown</span> on <span class="time">{time_text}</span></span>',
								'<p>{comment}</p>',
							'</li>',
						'</tpl>',
						'<tpl for="noComments">',
							'<li id="noCommentsLi"><p class="noBg">There are no comments. You should be the first one!</p></li>',
						'</tpl>',
					'</ul>',
					'<form id="makeCommentForm" method="post" action="http://adampassey.com/Sencha/game-store-mobile/api/comments/comments.php">',
						'<label for="inputComment">Make a comment</label>',
						'<input type="text" id="inputComment" name="inputComment" size="120" />',
						'<input type="submit" id="inputSubmit" name="inputSubmit" />',
						'<input type="hidden" id="game_id" name="game_id" value="{Id}" />',
						'<div id="makeCommentAjaxLoader"></div>',
						'<div class="clear"></div>',
					'</form>',
				'</div>',
				'<div class="cheatsContainer sectionContainer">',
					'<div class="cheatsInnerContainer"></div>',
				'</div>',
			'</div>',
]);